name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t tabnai007/my-python-app .

    - name: Push Docker image
      run: |
        docker push tabani007/my-python-app

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Git user
      run: |
        git config --global user.name "Heroku-Deploy"
        git config --global user.email "mointabani24@gmail.com"

    - name: Log in to Heroku
      uses: akhileshns/heroku-deploy@v3.9.9
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_email: mointabani24@gmail.com
        heroku_app_name: Demo Python App
        usedocker: true
